### PR TITLE
Allow edition of bonds without fetching it first.

### PR DESCRIPTION
**Pull request by JoProvost**
- Fix the case where a bond is created and then updated.
 - Adding switch calls by name instead of position parameters

### CODE REVIEW

**Comment by lindycoder** [comment]
This does address the Interface is none problem, but not the interface is missing stuff problem,

Here's a scenario:

add_bond(1)
bond = get_bond(1)
assert_that(bond.interface.name, is_("ae1")) //example for juniper

**Comment by lindycoder** [comment]
alternatively...

get_bonds() //caches
add_bond(1)
bonds = get_bonds()
bond1 = find_bond(1, bonds)
assert_that(bond.interface.name, is_("ae1")) //example for juniper

**Comment by JoProvost** [comment]
Exact, but how would you know the name of the bond without fetching it?  This is why we decided to give a number as identifiant of a bond. The interface object in a bond is there to represent all attributes related to an interface but the name was none of them.

**Comment by lindycoder** [comment]
So what you're saying is that the interface object in the bond should not have a name at all?

**Comment by JoProvost** [comment]
That's my point

**Comment by JoProvost** [comment]
The alternative is to avoid caching bond creation, this way, the name will be accurate in it's interface sub component.

**Comment by lindycoder** [comment]
interesting... is the interface in the bond still an interface?  i'm thinking of the liskov principle....  maybe all the attributes an interface have should be given to the bond... what about ...

class Interface(object):  everything but the 

class PhysicialInterface(Interface): Only have a name

class Bond(Interface):  have all the bond stuff

just a thought...

**Comment by JoProvost** [comment]
I agree with you, it makes sens and I also think that it's the way to go . Do you agree on moving all Interface's properties in the Bond class as part of another pull request?  I'll be more than happy to do it.

**Comment by lindycoder** [comment]
Ok agreed, :+1:

**Pull request merged**
